name: quran_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  image: ^4.1.3
  audioplayers: ^6.0.0
  msix: ^3.16.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Here is where we tell Flutter about your image and sound
  assets:
    - assets/Heart_Image.jpg
    - assets/check.wav

  # Here is where we tell Flutter to use your Arabic font
  fonts:
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma.ttf